### ISSUE TITLE
Unwelcome change in starting VFPX Deployment

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/VFPXDeployment#17]
I am quite displeased with a recent change in starting VFPX Deployment.

Previously, running VFPX Deployment brought up a dialog to find the project to deploy.  This was highly desirable.  I have multiple VFPX projects that I manage and I always want to choose the project to deploy.

The new behavior is to try to use the current folder to determine what project I am working in, looking to see where .git is defined in the parent structure.  This does not work at all for me; I am never working directly in the folder for the VFPX project I am going to deploy.

I do not mind at all the existence of this new behavior (I am sure it is appropriate for some users), but it should not be implemented at the expense of the old.  Furthermore, I think that care must be exercised when introducing new features not to change previous behaviors.

Please provide a mechanism so that the old behavior can still be available.  I suggest doing so by using a Thor option.

**Comment by lscheffler** [comment]
The former version was not searching for a project, it was requesting a folder, repeating until a folder that contains a .git subfolder (what does not mean this is under git control, btw, neither must a folder *.git* keep git data nor must the folder with the git data be named *.git*) was selected or the empty string returned.

The recent version does as follows:
1. Check if the recent folder is in a *git controlled folder structure*, same as if you would go into the bash, or a tool of your  choice and this will tell you in what branch you are - or not.
2.  If the recent folder is not in this, it will check if the active projects home folder (JUSTPATH of the pjx's FULLPATH) is a *git controlled folder structure*
3. If yes, the user will be asked if he likes to use this project
4. if no, or the user answers no, a folder name will be requested, and this folder will be asked to be in a  *git controlled folder structure*
5. if the empty string is returned, it will stop

So as it sounds, your recent folder is under git control and runs automatic, while you are in an environment where a project is on a different repository.    
All style discussions aside, I would not recommend this, I would rather choose a neutral place to run my projects from. What I do for the VFPX stuff, my regular projects are one project per folder and IDE.

So what I think I can do most simple is to ignore the recent folder, if the recent folder is not the git toplevel folder (If it is, it would run as before, except it does not focus on *.git* folder but on `git rev-parse --show-toplevel`).
Then next it would try the active project, or you can gice any folder in your repository. Would this help?

**Comment by lscheffler** [comment]
No problem. Since there are only very little people using this tool, we will just return to 1a9ead769c54752d0099576 *Update docs*, I set the docs for the projects I'm working on to my fork and I'm done.    
@DougHennig, can you reset this repo to the commit mentioned above ot do you need help for this?

**Comment by DougHennig** [comment]
@lscheffler Yes, I will need help to do this.

**Comment by lscheffler** [comment]
Hi Doug, sorry for the inconvenience.    
[Here](https://iotespresso.com/permanently-revert-github-branch-to-a-specific-commit/) is a description of the general idea or other ways then brute force reset.

Step by step (and in bash, I know nothing of GUI):
1. I assume you have a local clone of this repository, 
   - **if not** create one using the toll you normally use
3. Enter the *toplevel* - or base - folder of your local repository in Windows - FileExplorer, right-click, select *Git bash here*
4. Within the bash, enter :   
```
git pull
git reset --hard 1a9ead769c5
git push -f
```
If there is an error message after the push, just let me know, then we need to set github to accept the forced push

If not you might exit out and, if you cloned right now, delete the folders from your comp

**Comment by Jimrnelson** [comment]
If nothing has been done yet about reverting -- please don't.

I think it should be easy enough for me to add a Thor option so that both Lutz and I are satisfied.

Actually, it'll be a good example of creating a Thor option.

**Comment by DougHennig** [comment]
I haven't reverted yet.

**Comment by Jimrnelson** [comment]
Good, easy enough to leave it alone.

I'll get to my update when time permits.

**Comment by lscheffler** [comment]
See https://github.com/VFPX/VFPXDeployment/issues/17#issuecomment-1568505336, please do not address me any longer on this repositrory.
