### ISSUE TITLE
Where did this .gitignore file come from?  Why?

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/VFPXDeployment#23]
I spent quite a bit of time this morning trying to determine why some new files in ThorRepository were not showing up so that I could commit them to GitGub

Eventually, I found this file in "Installed Files"

![image](https://github.com/VFPX/VFPXDeployment/assets/81179335/3e7159ac-95d7-4468-934f-66a1d0c017df)

I did not create this file, but the timestamp on it matches exactly the last time I ran VFPX Deployment.  

What gives?  Why is VFPXDeploy creating .gitignore files?  Why in a sub-directory?  Why ignore everything in that sub-directory?

Clearly I can remove the file now, but I have to assume it will be re-created the next time I run VFPX Deploy.  And this simply does not work for me.

**Comment by lscheffler** [comment]
Program   
Simply to not include the InstalledFiles folder to the repo? This folder is just a bloat of the repo, and will be included by a `git add .` if not excluded. The file will not be inside the zip.

See https://github.com/VFPX/VFPXDeployment/blob/main/docs/ChangeLog.md#2023-05-22-version--1208542
> A .gitignore to keep the staging folder out of the repository.
> Note: If already in the repo, this will not remove the files!

**Comment by lscheffler** [comment]
Wait, you like to include this folder, if no InstalledFiles.txt is given? For the moment, just delete the gitignore and add new files to the repo. Files that are in the repo should get the change by a simple git add.   
I fix this.

**Comment by lscheffler** [comment]
With next version, the file will not be added, if no InstalledFiles.txt is given. Does this work for you?

**Comment by DougHennig** [comment]
Fixed in the latest version
