### ISSUE TITLE
No source given

### ISSUE THREAD

**Issue by lscheffler** [VFPX/VFPXDeployment#24]
## ℹ Computer information

- VFP version: VFP 9
- VFPX Deployment version: 1.2.08555

## 📝 Provide detailed reproduction steps (if any)

1. Create a project without BuildProcess/InstalledFiles.txt and without InstalledFiles folder
2. Run VFPXDeployment

### ✔️ Expected result

Some message

### ❌ Actual result

Just runs, but creates no zip

**Comment by lscheffler** [comment]
Ooops, all works as expected. Except that the zip tries to zip the -open- pjx and fails silently.

**Comment by DougHennig** [comment]
@lscheffler I do not think it is necessary to do extra handling. This is a utility that is used for one specific task, infrequently, so I do not think it would be a problem if it did not restore everything the way it was before it was run. The user can easily open whatever they need to reopen if necessary. No need to make the utility do everything anyone could ever think of.

**Comment by lscheffler** [comment]
It's just that I'm lazy. I run in the issue with PEMEditor - and dislike to remember it later. Or get confused if the zip is gone again. :)

I only think it might be overkill. I prefer that the prg complains if the zip is missing after zipping. I just liked to point out the options.

**Comment by Jimrnelson** [comment]
> @Jimrnelson , @DougHennig What do think is best solution
> 
> * simply close active project and reopen after
> * close all projects and reopen after
> * just check for the zip and complain if not created
> * just update the contributing of the project and state that the pjx must be closed
> 
> @DougHennig since we open and close projects here and elsewhere, how will this work with Project Explorer? Should one do some extra handling?

I don't have anything to contribute to this, as I prefer to tell VFPXDeploy what to do and not have it try to infer anything from my environment, and I certainly do not want it to change my environment.  For me, neither the current path or the active project (if any) matter.
