### ISSUE TITLE
Update description in CFU for VFPX Deployment is weird

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/VFPXDeployment#27]
Update description in CFU for VFPX Deployment is weird.

I expect to see the newest version number and date, but they are embedded strangely in the text, making it unreadable.

![image](https://github.com/VFPX/VFPXDeployment/assets/81179335/0fdb2402-7a8e-4438-bebd-0dd11ea2732b)

**Comment by DougHennig** [comment]
Fixed in the latest version.
