### ISSUE TITLE
Automatic update of version file with contents of ChangeLog had disappeared

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/VFPXDeployment#28]
One of the early features of VFPXDeploy, which copied the contents of ChangeLog.md into the version file, has disappeared.

The contents of the version file appear in CFU, as shown here for GoToDefinition

![image](https://github.com/VFPX/VFPXDeployment/assets/81179335/de567acf-d8bd-4a63-944f-646c62b5875f)

This change has occurred since May 20.  On that date, I updated Thor Repository and the change log was embedded into the version file, as expected.

Today, however, that is not occurring.

My version template file looks like this and has not changed since January.

![image](https://github.com/VFPX/VFPXDeployment/assets/81179335/8e80c261-e845-4048-af4f-989119efbe49)

**Comment by Jimrnelson** [comment]
I have identified the issue here -- your code for processing ProjectSettings.txt does not account for tabs in the file.

This could have been avoided easily enough using GetWordNum.

**Comment by DougHennig** [comment]
Fixed in the latest version.
