### ISSUE TITLE
FoxBin2PRG runs on InstalledFiles folder

### ISSUE THREAD

**Issue by DougHennig** [VFPX/VFPXDeployment#30]
## ℹ Computer information

- VFP version: any
- VFPX Deployment version: 1.4.08562

## 📝 Provide detailed reproduction steps (if any)

1. Specify "." for the FoxBin2PRGFolder setting in ProjectSettings.txt
2. Have an InstalledFiles.txt in the BuildProcess folder that specifies VFP binary files (e.g. VCX or SCX) to copy to the InstalledFiles folder
3. Run VFPX Deployment
4. Run VFPX Deployment a second time (the bug won't appear if InstalledFiles doesn't exist the first time)

### ✔️ Expected result

No VC2 or SC2 files are in the InstalledFiles folder since they were not specified in InstalledFiles.txt.

### ❌ Actual result

VC2 or SCX files are found in the InstalledFolder folder because when FoxBin2PRG processes the files in the project root folder (specified in step 1 above), it processes all subdirectories too, so it runs on the binary files copied into InstalledFiles. If possible, configure FoxBin2PRG to not process subdirectories (not sure if this is supported).

**Comment by Jimrnelson** [comment]
This should be a configuration item.  

I have a few projects where I am definitely interested in processing subdirectories.

**Comment by DougHennig** [comment]
I looked at FoxBin2PRG and it doesn't currently have an option to turn this off, so I'll close this issue.
